# Generated by Django 3.1 on 2020-09-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatros', '0002_area_doctor_patient_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='adress',
            new_name='address',
        ),
    ]
